#!/usr/local/bin/bash

source ./.set_vars_gon

denom=$1
entry_path=$2

if [[ ! -n $denom ]] || [[ ! -n $entry_path ]]; then
  echo "[ERROR]: use ./echo_path2.sh DENOME PATH"
  exit 1
fi

entry_path=$(./path-reducer.sh $entry_path)
declare -A PORT_CHANNEL_MATRIX 2>/dev/null

# =============== i -> others ===============
PORT_CHANNEL_MATRIX["is"]="wasm.$STARGAZE_PORT/$STARGAZE_TO_IRIS_CHANNEL_1"
PORT_CHANNEL_MATRIX["Is"]="wasm.$STARGAZE_PORT/$STARGAZE_TO_IRIS_CHANNEL_2"
PORT_CHANNEL_MATRIX["ij"]="wasm.$JUNO_PORT/$JUNO_TO_IRIS_CHANNEL_1"
PORT_CHANNEL_MATRIX["Ij"]="wasm.$JUNO_PORT/$JUNO_TO_IRIS_CHANNEL_2"
PORT_CHANNEL_MATRIX["io"]="nft-transfer/$OMNIFLIX_TO_IRIS_CHANNEL_1"
PORT_CHANNEL_MATRIX["Io"]="nft-transfer/$OMNIFLIX_TO_IRIS_CHANNEL_2"
PORT_CHANNEL_MATRIX["iu"]="nft-transfer/$UPTICK_TO_IRIS_CHANNEL_1"
PORT_CHANNEL_MATRIX["Iu"]="nft-transfer/$UPTICK_TO_IRIS_CHANNEL_2"

# =============== o -> others ===============
PORT_CHANNEL_MATRIX["os"]="wasm.$STARGAZE_PORT/$STARGAZE_TO_OMNIFLIX_CHANNEL_1"
PORT_CHANNEL_MATRIX["Os"]="wasm.$STARGAZE_PORT/$STARGAZE_TO_OMNIFLIX_CHANNEL_2"
PORT_CHANNEL_MATRIX["oj"]="wasm.$JUNO_PORT/$JUNO_TO_OMNIFLIX_CHANNEL_1"
PORT_CHANNEL_MATRIX["Oj"]="wasm.$JUNO_PORT/$JUNO_TO_OMNIFLIX_CHANNEL_2"
PORT_CHANNEL_MATRIX["oi"]="nft-transfer/$IRIS_TO_OMNIFLIX_CHANNEL_1"
PORT_CHANNEL_MATRIX["Oi"]="nft-transfer/$IRIS_TO_OMNIFLIX_CHANNEL_2"
PORT_CHANNEL_MATRIX["ou"]="nft-transfer/$UPTICK_TO_OMNIFLIX_CHANNEL_1"
PORT_CHANNEL_MATRIX["Ou"]="nft-transfer/$UPTICK_TO_OMNIFLIX_CHANNEL_2"

# =============== u -> others ===============
PORT_CHANNEL_MATRIX["us"]="wasm.$STARGAZE_PORT/$STARGAZE_TO_UPTICK_CHANNEL_1"
PORT_CHANNEL_MATRIX["Us"]="wasm.$STARGAZE_PORT/$STARGAZE_TO_UPTICK_CHANNEL_2"
PORT_CHANNEL_MATRIX["uj"]="wasm.$JUNO_PORT/$JUNO_TO_UPTICK_CHANNEL_1"
PORT_CHANNEL_MATRIX["Uj"]="wasm.$JUNO_PORT/$JUNO_TO_UPTICK_CHANNEL_2"
PORT_CHANNEL_MATRIX["ui"]="nft-transfer/$IRIS_TO_UPTICK_CHANNEL_1"
PORT_CHANNEL_MATRIX["Ui"]="nft-transfer/$IRIS_TO_UPTICK_CHANNEL_2"
PORT_CHANNEL_MATRIX["uo"]="nft-transfer/$OMNIFLIX_TO_UPTICK_CHANNEL_1"
PORT_CHANNEL_MATRIX["Uo"]="nft-transfer/$OMNIFLIX_TO_UPTICK_CHANNEL_2"

# =============== s -> others ===============
PORT_CHANNEL_MATRIX["su"]="nft-transfer/$UPTICK_TO_STARGAZE_CHANNEL_1"
PORT_CHANNEL_MATRIX["Su"]="nft-transfer/$UPTICK_TO_STARGAZE_CHANNEL_2"
PORT_CHANNEL_MATRIX["sj"]="wasm.$JUNO_PORT/$JUNO_TO_STARGAZE_CHANNEL_1"
PORT_CHANNEL_MATRIX["Sj"]="wasm.$JUNO_PORT/$JUNO_TO_STARGAZE_CHANNEL_2"
PORT_CHANNEL_MATRIX["si"]="nft-transfer/$IRIS_TO_STARGAZE_CHANNEL_1"
PORT_CHANNEL_MATRIX["Si"]="nft-transfer/$IRIS_TO_STARGAZE_CHANNEL_2"
PORT_CHANNEL_MATRIX["so"]="nft-transfer/$OMNIFLIX_TO_STARGAZE_CHANNEL_1"
PORT_CHANNEL_MATRIX["So"]="nft-transfer/$OMNIFLIX_TO_STARGAZE_CHANNEL_2"

# =============== j -> others ===============
PORT_CHANNEL_MATRIX["ju"]="nft-transfer/$UPTICK_TO_JUNO_CHANNEL_1"
PORT_CHANNEL_MATRIX["Ju"]="nft-transfer/$UPTICK_TO_JUNO_CHANNEL_2"
PORT_CHANNEL_MATRIX["js"]="wasm.$STARGAZE_PORT/$STARGAZE_TO_JUNO_CHANNEL_1"
PORT_CHANNEL_MATRIX["Js"]="wasm.$STARGAZE_PORT/$STARGAZE_TO_JUNO_CHANNEL_2"
PORT_CHANNEL_MATRIX["ji"]="nft-transfer/$IRIS_TO_JUNO_CHANNEL_1"
PORT_CHANNEL_MATRIX["Ji"]="nft-transfer/$IRIS_TO_JUNO_CHANNEL_2"
PORT_CHANNEL_MATRIX["jo"]="nft-transfer/$OMNIFLIX_TO_JUNO_CHANNEL_1"
PORT_CHANNEL_MATRIX["Jo"]="nft-transfer/$OMNIFLIX_TO_JUNO_CHANNEL_2"

FULL_PATH=""
for ((i = 0; i < ${#entry_path}; i++)); do
  CH="${entry_path:$i:2}"
  #echo $CH
  SEG=${PORT_CHANNEL_MATRIX[$CH]}

  if [ -n "$SEG" ]; then
    FULL_PATH=$SEG/$FULL_PATH
  fi
done

echo $FULL_PATH$denom
